
name: prueba

on:
  push:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: hola esto es una prueba 

      - name: Run a multi-line script
        run: |
          echo prueba1,
          time
          touch prueba.txt
          ls-la
